connector.name=iceberg
iceberg.catalog.type=rest
iceberg.rest-catalog.uri=https://s3tables.ap-southeast-1.amazonaws.com/iceberg
iceberg.rest-catalog.warehouse=<ARN_S3_TABLES_BUCKET>
iceberg.rest-catalog.security=SIGV4
iceberg.rest-catalog.signing-name=s3tables
fs.native-s3.enabled=true
s3.region=ap-southeast-1
s3.aws-access-key=${ENV:AWS_ACCESS_KEY_ID}
s3.aws-secret-key=${ENV:AWS_SECRET_ACCESS_KEY}
iceberg.dynamic-filtering.wait-timeout=1m
iceberg.metadata-cache-ttl=60s

# S3 parallelism
s3.max-connections=2000
s3.socket-timeout=60s
s3.max-error-retries=10

# Parquet read tuning
parquet.use-column-index=true
parquet.use-bloom-filter=true
parquet.max-read-block-size=16MB
parquet.optimized-reader.enabled=true
parquet.vectorized-reader.enabled=true
parquet.vectorized-reader.batch-size=1024
