coordinator=true
node-scheduler.include-coordinator=true
http-server.http.port=8080
discovery.uri=http://localhost:8080

# heap = 1024G; headroom 100G; query budget 900G
query.max-memory=900GB
query.max-memory-per-node=900GB
memory.heap-headroom-per-node=100GB

# 192 vCPU box
task.concurrency=64
task.max-worker-threads=192
task.max-writer-count=8

# more concurrent splits per node for big S3 scans
node-scheduler.max-splits-per-node=2048
node-scheduler.min-pending-splits-per-task=32

# long client polls
query.client.timeout=30m
